# 1. Build de l'application React
FROM node:18-alpine AS build

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
# En production, on appelle le backend sur /api au lieu de localhost:8080 (proxy inverse via Nginx)
ENV VITE_API_URL=/api/v1
RUN npm run build

# 2. Serveur Nginx
FROM nginx:alpine

# Copie de la configuration Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copie des fichiers statiques générés
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
